name: rarehunter_app
description: "RareHunter — MVP для поиска редких предметов"
publish_to: 'none' # чтобы не залить случайно на pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

  # Базовые иконки iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Здесь позже можно будет добавить ассеты:
  # assets:
  #   - assets/images/
  #
  # и кастомные шрифты:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700